rabbit:
  uri: ${RABBIT_URI}
  queue:
    ttl: 120000

http:
  auth-token: ${ACCESS_TOKEN:ticktok-zY3wpR}

spring:
  profiles:
    active: rabbit
  data:
    mongodb:
      uri: ${MONGO_URI}

queues:
  ttl: 120000


management:
  health:
    defaults:
      enabled: false
    mongo:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
      base-path: /mgmt

clocks:
  purge:
    interval: 120000

schedules:
  purge:
    interval: 3600000

ticks:
  purge:
    interval: 43200000
    keepCount: 10

