rabbit:
  uri: ${RABBIT_URI}
  queue:
    ttl: 120

http:
  auth-token: ${ACCESS_TOKEN}
  domain: ${SELF_DOMAIN}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

management:
  endpoints:
    web:
      base-path: /mgmt

