version: '3'

services:
  app:
    image: app
    ports:
      - 9643:9643
    environment:
      - RABBIT_URI=amqp://rabbit
      - MONGO_URI=mongodb://mongo/e2e-test
      - ACCESS_TOKEN=${E2E_ACCESS_TOKEN}
      - RABBIT_CONSUMERURI=amqp://localhost
      - RABBIT_QUEUE_TTL=1000
      - CLOCKS_PURGE_INTERVAL=4000
      - SCHEDULES_PURGE_INTERVAL=250
      - TICKS_PURGE_INTERVAL=500
      - TICKS_PURGE_KEEPCOUNT=1
    depends_on:
      - rabbit
      - mongo
